name: Code Analysis
on: [pull_request]
jobs:
  ESLint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - run: echo "Scanning code of branch ${{ github.ref }}."
      - name: Run ESLint
        run: npx eslint src --ext ts
