name: Code Analysis
on: [pull_request]
jobs:
  ESLint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "Scanning code of branch ${{ github.repository }}/${{ github.ref }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Code Analysis
        run: |
          npm run lint
