name: Code Analysis
on: [pull_request]
jobs:
  ESLint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Scanning code of branch ${{ github.ref }}."
      - name: Install
        run: npm install
      - name: Run ESLint
        run: npm run lint
